name: test

on: [push, pull_request]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Forge build
        run: |
          forge --version
          forge build --use 0.5.12 --out out/0-5-12 --skip script/* test/* test/mocks/* --contracts lib/osm/src && forge build --out out
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
